### ISSUE TITLE
blog-example crashing

### ISSUE THREAD

**Issue by Aidurber** [Differential/meteor-blog#190]
When trying to view the example it's crashing. 

I'm sure this info isn't important but: 
OS: Windows 8.1
Browser: Chrome 43.0.2357.130 m
![image](https://cloud.githubusercontent.com/assets/5732291/8376138/c5bfa478-1bfb-11e5-9d76-0cff18ddd91e.png)

**Comment by Neobii** [comment]
It's probably cause of this package vsivsi:file-collection, which also makes it crash when I deploy to modulus.

**Comment by hellogerard** [comment]
There is a known issue for Modulus deploys, but I didn't know it broke on meteor.com as well. It shouldn't.

**Comment by hellogerard** [comment]
@rgoomar Rishi, you deployed that site. I can't get to the logs, or attempt to restart it. Can you take a look?

**Comment by vsivsi** [comment]
The file-collection package shouldn't cause any problems when deployed to meteor.com. If you have evidence that it does, please file an issue with a reproducing repo and I'll look into it. 

@hellogerard  Has reported issues deploying an app using file-collection with demeteorizer, but last I heard that was an issue with demeteorizer not respecting that different atmosphere packages may require different, incompatible npm dependencies. If so, that's definitely a demeteorizer bug.  I've deployed file-collection apps using Meteor-up (mup) without difficulty.

**Comment by vsivsi** [comment]
@Neobii  The issue using file-collection on Modulus is a bug in how demeteorizer handles npm dependencies.  https://github.com/onmodulus/demeteorizer/issues/125

**Comment by rgoomar** [comment]
Here are the logs from the blog example:
```
[Fri Jul 03 2015 14:22:22 GMT+0000 (UTC)] WARNING TypeError: Cannot call method 'indexOf' of undefined
at __coffeescriptShare (packages/ryw:blog/server/boot.coffee:55:13)
at /meteor/containers/945f1b1c-5cda-b9b7-4e2a-9719485b268b/bundle/programs/server/boot.js:229:5
[Fri Jul 03 2015 14:22:27 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Fri Jul 03 2015 14:22:27 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Fri Jul 03 2015 14:22:37 GMT+0000 (UTC)] INFO HIT / 117.203.239.111
[Fri Jul 03 2015 14:22:43 GMT+0000 (UTC)] INFO HIT / 117.203.239.111
[Fri Jul 03 2015 14:22:44 GMT+0000 (UTC)] INFO HIT /favicon.ico 117.203.239.111
[Fri Jul 03 2015 14:22:50 GMT+0000 (UTC)] INFO HIT /favicon.ico 117.203.239.111
[Fri Jul 03 2015 14:22:54 GMT+0000 (UTC)] NOTICE Starting application on port 13309
[Fri Jul 03 2015 14:22:54 GMT+0000 (UTC)] INFO STATUS waiting -> starting
[Fri Jul 03 2015 14:22:54 GMT+0000 (UTC)] INFO STATUS starting -> running
[Fri Jul 03 2015 14:22:55 GMT+0000 (UTC)] WARNING
/meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
throw(ex);
^
[Fri Jul 03 2015 14:22:55 GMT+0000 (UTC)] WARNING TypeError: Cannot call method 'indexOf' of undefined
at __coffeescriptShare (packages/ryw:blog/server/boot.coffee:55:13)
at /meteor/containers/945f1b1c-5cda-b9b7-4e2a-9719485b268b/bundle/programs/server/boot.js:229:5
[Fri Jul 03 2015 14:22:56 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Fri Jul 03 2015 14:22:56 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Fri Jul 03 2015 14:23:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:23:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:24:07 GMT+0000 (UTC)] INFO STATUS waiting -> starting
[Fri Jul 03 2015 14:24:07 GMT+0000 (UTC)] NOTICE Starting application on port 13309
[Fri Jul 03 2015 14:24:07 GMT+0000 (UTC)] INFO STATUS starting -> running
[Fri Jul 03 2015 14:24:18 GMT+0000 (UTC)] WARNING /meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
throw(ex);
^
[Fri Jul 03 2015 14:24:18 GMT+0000 (UTC)] WARNING TypeError: Cannot call method 'indexOf' of undefined
at __coffeescriptShare (packages/ryw:blog/server/boot.coffee:55:13)
at /meteor/containers/945f1b1c-5cda-b9b7-4e2a-9719485b268b/bundle/programs/server/boot.js:229:5
[Fri Jul 03 2015 14:24:18 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Fri Jul 03 2015 14:24:18 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Fri Jul 03 2015 14:24:47 GMT+0000 (UTC)] INFO HIT / 117.203.239.111
[Fri Jul 03 2015 14:24:53 GMT+0000 (UTC)] INFO HIT / 117.203.239.111
[Fri Jul 03 2015 14:24:53 GMT+0000 (UTC)] INFO HIT /favicon.ico 117.203.239.111
[Fri Jul 03 2015 14:24:59 GMT+0000 (UTC)] INFO HIT /favicon.ico 117.203.239.111
[Fri Jul 03 2015 14:26:52 GMT+0000 (UTC)] NOTICE Starting application on port 13309
[Fri Jul 03 2015 14:26:52 GMT+0000 (UTC)] INFO STATUS waiting -> starting
[Fri Jul 03 2015 14:26:52 GMT+0000 (UTC)] INFO STATUS starting -> running
[Fri Jul 03 2015 14:26:54 GMT+0000 (UTC)] WARNING /meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
throw(ex);
^
[Fri Jul 03 2015 14:26:54 GMT+0000 (UTC)] WARNING TypeError: Cannot call method 'indexOf' of undefined
at __coffeescriptShare (packages/ryw:blog/server/boot.coffee:55:13)
at /meteor/containers/945f1b1c-5cda-b9b7-4e2a-9719485b268b/bundle/programs/server/boot.js:229:5
[Fri Jul 03 2015 14:26:59 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Fri Jul 03 2015 14:26:59 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Fri Jul 03 2015 14:28:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:28:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:32:34 GMT+0000 (UTC)] NOTICE Starting application on port 13309
[Fri Jul 03 2015 14:32:34 GMT+0000 (UTC)] INFO STATUS waiting -> starting
[Fri Jul 03 2015 14:32:35 GMT+0000 (UTC)] INFO STATUS starting -> running
[Fri Jul 03 2015 14:32:36 GMT+0000 (UTC)] WARNING                         throw(ex);
^
[Fri Jul 03 2015 14:32:36 GMT+0000 (UTC)] WARNING
/meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
[Fri Jul 03 2015 14:32:36 GMT+0000 (UTC)] WARNING TypeError: Cannot call method 'indexOf' of undefined
at __coffeescriptShare (packages/ryw:blog/server/boot.coffee:55:13)
at /meteor/containers/945f1b1c-5cda-b9b7-4e2a-9719485b268b/bundle/programs/server/boot.js:229:5
[Fri Jul 03 2015 14:32:36 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Fri Jul 03 2015 14:32:36 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Fri Jul 03 2015 14:33:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:33:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:38:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:38:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:43:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:43:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:44:26 GMT+0000 (UTC)] NOTICE Starting application on port 13309
[Fri Jul 03 2015 14:44:26 GMT+0000 (UTC)] INFO STATUS waiting -> starting
[Fri Jul 03 2015 14:44:26 GMT+0000 (UTC)] INFO STATUS starting -> running
[Fri Jul 03 2015 14:44:27 GMT+0000 (UTC)] WARNING      ^
[Fri Jul 03 2015 14:44:27 GMT+0000 (UTC)] WARNING                         throw(ex);
[Fri Jul 03 2015 14:44:27 GMT+0000 (UTC)] WARNING /meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
[Fri Jul 03 2015 14:44:28 GMT+0000 (UTC)] WARNING TypeError: Cannot call method 'indexOf' of undefined
at __coffeescriptShare (packages/ryw:blog/server/boot.coffee:55:13)
at /meteor/containers/945f1b1c-5cda-b9b7-4e2a-9719485b268b/bundle/programs/server/boot.js:229:5
[Fri Jul 03 2015 14:44:28 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Fri Jul 03 2015 14:44:28 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Fri Jul 03 2015 14:48:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:48:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:53:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:53:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:58:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 14:58:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:03:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:03:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:06:40 GMT+0000 (UTC)] NOTICE Starting application on port 13309
[Fri Jul 03 2015 15:06:40 GMT+0000 (UTC)] INFO STATUS waiting -> starting
[Fri Jul 03 2015 15:06:40 GMT+0000 (UTC)] INFO STATUS starting -> running
[Fri Jul 03 2015 15:06:46 GMT+0000 (UTC)] WARNING /meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
throw(ex);
^
[Fri Jul 03 2015 15:06:46 GMT+0000 (UTC)] WARNING TypeError: Cannot call method 'indexOf' of undefined
at __coffeescriptShare (packages/ryw:blog/server/boot.coffee:55:13)
at /meteor/containers/945f1b1c-5cda-b9b7-4e2a-9719485b268b/bundle/programs/server/boot.js:229:5
[Fri Jul 03 2015 15:06:51 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Fri Jul 03 2015 15:06:51 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Fri Jul 03 2015 15:08:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:08:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:13:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:13:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:18:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:18:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:23:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:23:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:28:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:28:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:33:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:33:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:38:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:38:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:43:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:43:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:48:02 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:48:08 GMT+0000 (UTC)] INFO HIT / 74.86.158.110
[Fri Jul 03 2015 15:49:31 GMT+0000 (UTC)] INFO HIT / 71.57.47.141
[Fri Jul 03 2015 15:49:37 GMT+0000 (UTC)] INFO HIT / 71.57.47.141
[Fri Jul 03 2015 15:49:37 GMT+0000 (UTC)] INFO HIT /favicon.ico 71.57.47.141
[Fri Jul 03 2015 15:49:43 GMT+0000 (UTC)] INFO HIT /favicon.ico 71.57.47.141
```
Seems to be [this line](https://github.com/Differential/meteor-blog/blob/master/server/boot.coffee#L55) that is causing the issue.

**Comment by rgoomar** [comment]
It should be working now
