### ISSUE TITLE
my app is crashing after added blog

### ISSUE THREAD

**Issue by suzurini** [Differential/meteor-blog#211]
Your app is crashing. Here's the latest log.

Meteor._wrapAsync has been renamed to Meteor.wrapAsync

/Users/Ksenechka/.meteor/packages/meteor-tool/.1.1.4.35khx9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: A method named '/roles/insert' is already defined
    at packages/ddp/livedata_server.js:1461:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at [object Object]._.extend.methods (packages/ddp/livedata_server.js:1459:1)
    at [object Object].Mongo.Collection._defineMutationMethods (packages/mongo/collection.js:904:1)
    at new Mongo.Collection (packages/mongo/collection.js:209:1)
    at [object Object].ns.Collection (packages/matb33:collection-hooks/collection-hooks.js:190:1)
    at Roles (packages/alanning:roles/roles_server.js:9:1)
    at packages/alanning:roles/roles_server.js:27:1
    at /Users/Ksenechka/gembets/.meteor/local/build/programs/server/packages/alanning_roles.js:49:4
    at /Users/Ksenechka/gembets/.meteor/local/build/programs/server/packages/alanning_roles.js:778:3
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by rgoomar** [comment]
Seems to be coming from the `alanning:roles` package. Would you mind creating a quick reproduction that we can clone down and test?

**Comment by hellogerard** [comment]
@suzurini  Are you on 1.2? Can you clone this repo and try it again on `master`?
