### ISSUE TITLE
error on fast-rendering

### ISSUE THREAD

**Issue by Silverutm** [Differential/meteor-blog#293]
error on fast-rendering path: / ; error: TypeError: Meteor.uuid is not a function
W20180317-20:24:47.264(-6)? (STDERR)     at new PublishContext (packages/meteorhacks_fast-render.js:348:17)
W20180317-20:24:47.264(-6)? (STDERR)     at packages/meteorhacks_fast-render.js:313:28
W20180317-20:24:47.265(-6)? (STDERR)     at Array.forEach (<anonymous>)
W20180317-20:24:47.265(-6)? (STDERR)     at Context.<anonymous> (packages/meteorhacks_fast-render.js:311:18)
W20180317-20:24:47.266(-6)? (STDERR)     at packages/meteorhacks_fast-render.js:286:18
W20180317-20:24:47.266(-6)? (STDERR)     at Array.forEach (<anonymous>)
W20180317-20:24:47.267(-6)? (STDERR)     at packages/meteorhacks_fast-render.js:285:31
W20180317-20:24:48.192(-6)? (STDERR) error on fast-rendering path: / ; error: TypeError: Meteor.uuid is not a function
W20180317-20:24:48.193(-6)? (STDERR)     at new PublishContext (packages/meteorhacks_fast-render.js:348:17)
W20180317-20:24:48.193(-6)? (STDERR)     at packages/meteorhacks_fast-render.js:313:28
W20180317-20:24:48.193(-6)? (STDERR)     at Array.forEach (<anonymous>)
W20180317-20:24:48.194(-6)? (STDERR)     at Context.<anonymous> (packages/meteorhacks_fast-render.js:311:18)
W20180317-20:24:48.194(-6)? (STDERR)     at packages/meteorhacks_fast-render.js:286:18
W20180317-20:24:48.195(-6)? (STDERR)     at Array.forEach (<anonymous>)
W20180317-20:24:48.195(-6)? (STDERR)     at packages/meteorhacks_fast-render.js:285:31

**Comment by ryanbraving** [comment]
I am getting the same error! Any update?

**Comment by Silverutm** [comment]
Someone suggested to change `staringatlights:fast-render` for `staringatlights:fast-render`, downloading the package and changing the file where the dependencies are.
[Issue on fast render, possible solution](https://github.com/abecks/meteor-fast-render/issues/22)
Haven't tried yet, but may be an option.
